### ISSUE TITLE
Support PostgreSQL 10+ versions

### ISSUE THREAD

**Issue by varjoranta** [spotify/postgresql-metrics#17]
Psycopg2 doesn't seem to work with more recent versions (10/11+) of libpq-dev. This requires experimentation and maybe replacing psycopg2 with something else more generic. For per-minute metrics purposes we don't need high performance, but simplicity and maintainability with future PostgreSQL versions.

**Comment by bfelbo** [comment]
I'm thinking of using this library with PostgreSQL 10. Did you ever get it to work?

**Comment by varjoranta** [comment]
There is PR open to fix this: https://github.com/spotify/postgresql-metrics/pull/20

**Comment by varjoranta** [comment]
This issue is solved on #20. Closing.
