### ISSUE TITLE
Hi, thanks for contributing this

### ISSUE THREAD

**Issue by perlchild** [spotify/postgresql-metrics#2]
This looks very interesting and promising.  However, would you mind clarifying the prerequisites? Does it need a specific version of python or postgres?

**Comment by varjoranta** [comment]
We have this currently deployed on Postgres 9.3 and 9.4 clusters with latest Python 2.7, and haven't tested with other versions. Most likely it will work with all 9.x versions, but I can update this answer when I find out more. I can also add a prerequisites section into the readme a bit later.

**Comment by varjoranta** [comment]
I added the prerequisites section, even it is rather limited at the moment. Postgresql-metrics is rather simple tool though, so the expected prerequisites should be minimal.
